// Generated by CoffeeScript 1.7.1
(function() {
  define(["knockout", "moment"], function(ko, moment) {
    var ClockViewModel;
    return ClockViewModel = (function() {
      function ClockViewModel() {
        this.now = ko.observable(moment());
        this.hour = ko.computed((function(_this) {
          return function() {
            return _this.now().format('HH:mm:ss');
          };
        })(this));
        this.date = ko.computed((function(_this) {
          return function() {
            return _this.now().format('LLLL');
          };
        })(this));
        ({
          updateClock: (function(_this) {
            return function() {
              return _this.now(moment());
            };
          })(this)
        });
      }

      setInterval(ClockViewModel.updateClock, 999);

      return ClockViewModel;

    })();
  });

}).call(this);

//# sourceMappingURL=clock.map
