// Generated by CoffeeScript 1.7.1
(function() {
  var ClockViewModel;

  ClockViewModel = (function() {
    function ClockViewModel() {
      this.now = ko.observable();
      this.hour = ko.computed((function(_this) {
        return function() {
          return _this.now.format('HH:mm:ss');
        };
      })(this));
      this.date = ko.computed((function(_this) {
        return function() {
          return _this.now.format('L L L L');
        };
      })(this));
      ({
        updateClock: (function(_this) {
          return function() {
            return _this.now(moment());
          };
        })(this)
      });
    }

    setInterval(ClockViewModel.updateClock, 999);

    return ClockViewModel;

  })();

  $(function() {
    return ko.applyBindings(new ClockViewModel);
  });

}).call(this);

//# sourceMappingURL=clock.map
