// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: "",
    paths: {
      "text": "app/lib/text",
      "knockout": "app/lib/knockout",
      "jquery": "app/lib/jquery",
      "moment": "app/lib/moment"
    }
  });

  define(["jquery", "knockout"], function($, ko) {
    var registerComponent;
    registerComponent = function(name) {
      return ko.components.register(name, {
        template: {
          require: "text!app/component/" + name + "/" + name + ".html"
        },
        viewModel: {
          require: "app/component/" + name + "/" + name
        }
      });
    };
    registerComponent("bus");
    registerComponent("clock");
    registerComponent("weather");
    return ko.applyBindings();
  });

}).call(this);

//# sourceMappingURL=startup.map
