// Generated by CoffeeScript 1.7.1
(function() {
  var BusViewModel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BusViewModel = (function() {
    var tripQuestion;

    function BusViewModel() {
      this.updateBusSchedule = __bind(this.updateBusSchedule, this);
      this.bus = ko.observableArray();
    }

    tripQuestion = 'https://api.vasttrafik.se/bin/rest.exe/v1/departureBoard?id=.kvil&format=json&jsonpCallback=?&direction=.anekd&authKey=5914945f-3e58-4bbc-8169-29571809775d&needJourneyDetail=0&timeSpan=1439&maxDeparturesPerLine=4';

    BusViewModel.prototype.updateBusSchedule = function() {
      return $.getJSON(tripQuestion(this.bus));
    };

    setInterval(BusViewModel.updateBusSchedule(100000));

    return BusViewModel;

  })();

  $(function() {
    return ko.applyBindings(new BusViewModel);
  });

}).call(this);

//# sourceMappingURL=bus.map
